// console.log("this is it")
// promise and async
/*
const myPromise = new Promise((resolve,reject) =>{
    console.log(typeof reject)
    setTimeout(() => {
        return reject("Rejected")
    },2000)
    return resolve("the code ran successfully")
})

myPromise.then(function(){
    console.log("The code ran successfully")
},function(){
    console.error("ErrorOccurredinsidePromise")
})
*/
